Avoid using java.text.SimpleDateFormat
republique-et-canton-de-geneve/chvote-1-0 pull request #24
Opened 2017-04-18 20:56 UTC by nremond

It's preferable as the class is not thread-safe, cf: https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html#synchronization.

2017-04-19 07:14 UTC, chvote-etat-de-geneve commented
Hello,

Thank you for your pull request. As we are using Java 8, we would prefer to use java.time.format.DateTimeFormatter over joda time.

That being said, OutputFilesPattern instances are never involved in multi-threaded contexts, so using SimpleDateFormat is not an immediate problem. It could arise if the class is badly used in future developments.

2017-04-19 07:24 UTC, nremond commented
OK, I can migrate that code to Java 8

2017-05-01 10:31 UTC, nremond commented
What do you think of that? I migrated the code to only use `java.time` package

2017-05-02 06:51 UTC, chvote-etat-de-geneve requested changes
Aside from variable names changes requested for consistency, this looks good.

2017-05-02 06:51 UTC, chvote-etat-de-geneve commented on admin-offline/src/main/java/ch/ge/ve/offlineadmin/controller/BallotDecryptionController.java
> +    private ZoneId ChZoneId = ZoneId.of("Europe/Zurich");
The variable name is not consistent with the naming of the other variables.
Would you consider changing it to `chZoneId` ?

2017-05-02 06:51 UTC, chvote-etat-de-geneve commented on admin-offline/src/main/java/ch/ge/ve/offlineadmin/controller/KeyGenerationController.java
> +    private ZoneId ChZoneId = ZoneId.of("Europe/Zurich");
Same comment here. Maybe change the variable to `chZoneId` for naming consistency?

2017-05-02 06:52 UTC, chvote-etat-de-geneve commented
Thanks for this PR, it looks good. If you'd be willing to change those fields' names, we'll gladly merge it!

2017-05-02 09:05 UTC, nremond commented
Done and rebased everything in a single commit.

2017-05-02 12:21 UTC, chvote-etat-de-geneve approved these changes

2017-05-02 12:21 UTC, merged

2017-05-02 12:22 UTC, chvote-etat-de-geneve commented
Merged, thank you!

2019-10-10 20:37 UTC, anthonydill10 commented
Add $5,000

2019-10-10 20:38 UTC, anthonydill10 commented
https://documentcloud.adobe.com/link/track?uri=urn%3Aaaid%3Ascds%3AUS%3A03dae309-74c3-4774-8c80-c60de45192e4